name: Scheduled Workflow
on:
  schedule:
    - cron: '30 5,17 * * *'

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run [   Hello Worlds]
      run: echo "Hello, world!"