name: Scheduled Workflow
on:
  schedule:
    - cron: '* * * * *'

#   workflow_dispatch: 
#   push:
#     branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run [   Hello Worlds]
      run: echo "Hello, world!"